<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PF1P3TA" failures="1" tests="4" name="Tests1" time="12.628" errors="0" timestamp="2025-07-24T05:52:22 IST">
  <testcase classname="api.test.DataDrivenTest" name="testPostUser" time="3.128"/>
  <testcase classname="api.test.DataDrivenTest" name="testPostUser" time="1.268"/>
  <testcase classname="api.test.DataDrivenTest" name="testDeleteUserByName" time="1.235">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTest.testDeleteUserByName(DataDrivenTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.DataDrivenTest" name="testDeleteUserByName" time="1.128"/>
</testsuite> <!-- Tests1 -->
